### ISSUE TITLE
angel_train.py error

### ISSUE THREAD

**Issue by Trandamere** [PacificBiosciences/ANGEL#13]
```
angel_train.py test.FG.dumb.final.traning.cds test.FG.dumb.final.traning.utr test.FG.dumb.final.classifier.pickle --cpus 10
```

```
Traceback (most recent call last):
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/bin/angel_train.py", line 4, in <module>
    __import__('pkg_resources').run_script('Angel==2.4', 'angel_train.py')
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/Angel-2.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/angel_train.py", line 17, in <module>
    ANGEL_training(args.cds_filename, args.utr_filename, args.output_pickle, num_workers=args.cpus)
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/Angel-2.4-py2.7-linux-x86_64.egg/Angel/SmartORF.py", line 97, in ANGEL_training
    data_neg = get_data_parallel(o_all, utr, [0, 1, 2], num_workers)
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/Angel-2.4-py2.7-linux-x86_64.egg/Angel/SmartORF.py", line 61, in get_data_parallel
    obj = queue.get(timeout=60)
  File "/disk/luping/tools/Python-2.7.14/lib/python2.7/multiprocessing/queues.py", line 132, in get
    raise Empty
Queue.Empty
```
I don't konw how to fix it!

**Comment by Trandamere** [comment]
It's normal when I run part of files

**Comment by Magdoll** [comment]
Is it possible to share the data? email to etseng@pacb.com.

**Comment by Trandamere** [comment]
Hi:
 I've solved it. Thank you very much!

**Comment by ClearloveMiao** [comment]
@Trandamere How do you fix this issue? I have encountered the same issue as yours. Thanks a lot!
