### ISSUE TITLE
angel_predict.py ：max_depth

### ISSUE THREAD

**Issue by MaPengyu** [PacificBiosciences/ANGEL#24]
Hi @Magdoll ,I got KeyError: 'max_depth'
`$angel_predict.py test.fa MCF7_2015.dumb.final.training.pickle test_angel
Reading classifer pickle: MCF7_2015.dumb.final.training.pickle
Traceback (most recent call last):
  File "/share/home/mpy/anaconda2/envs/anaCogent/bin/angel_predict.py", line 4, in <module>
    __import__('pkg_resources').run_script('Angel==2.4', 'angel_predict.py')
  File "/share/home/mpy/anaconda2/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/share/home/mpy/anaconda2/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/share/home/mpy/anaconda2/envs/anaCogent/lib/python2.7/site-packages/Angel-2.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/angel_predict.py", line 22, in <module>
    distribute_ANGEL_predict(args.fasta_filename, args.output_prefix, args.classifier_pickle, args.cpus, args.min_angel_aa_length, args.min_dumb_aa_length, args.use_rev_strand, args.output_mode, args.max_angel_secondORF_distance)
  File "/share/home/mpy/anaconda2/envs/anaCogent/lib/python2.7/site-packages/Angel-2.4-py2.7-linux-x86_64.egg/Angel/SmartORF.py", line 238, in distribute_ANGEL_predict
    a = load(f)
  File "sklearn/tree/_tree.pyx", line 649, in sklearn.tree._tree.Tree.__setstate__
KeyError: 'max_depth'
`

**Comment by Magdoll** [comment]
This should not be an issue after re-compiling. If issue persists, please notify.

--liz
