### ISSUE TITLE
Fatal error at dumb_predict.py

### ISSUE THREAD

**Issue by veravelasco** [PacificBiosciences/ANGEL#31]
Hi I am getting fatal error.  Is this an installation error or something wrong with my input file? I used fasta.gz of polished isoforms. Thanks.

Traceback (most recent call last):
  File "/isg/shared/apps/angel/2.7/bin/dumb_predict.py", line 4, in <module>
    __import__('pkg_resources').run_script('Angel==2.7', 'dumb_predict.py')
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/EGG-INFO/scripts/dumb_predict.py", line 18, in <module>
    transdecoder_main(args.fasta_filename, args.output_prefix, args.min_aa_length, args.use_rev_strand, args.use_firstORF, args.cpus)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/DumbORF.py", line 169, in transdecoder_main
    result = predict_longest_ORFs(seq, min_aa_length, use_firstORF) # result is {best_frame: [(best_flag, best_s, best_e)]}
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/ORFutils.py", line 17, in g
    raise TypeError, "Input string must consist of only ATCG!"
TypeError: Input string must consist of only ATCG!
running CD-HIT to generate non-redundant set....

Fatal Error:
Failed to open the database file
Program halted !!

**Comment by Magdoll** [comment]
Hi @veravelasco ,

Only fasta input is accepted. No compression allowed.

Thanks,
--Liz
