### ISSUE TITLE
error on angel_train.py, pickle not produced

### ISSUE THREAD

**Issue by veravelasco** [PacificBiosciences/ANGEL#32]
Hi,  Please let me know what this error is about?  Its seems like some parts of the process for angel_train.py worked but ultimately there is no pickle produced.  Thanks in advance.

/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Bio/Seq.py:2715: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
running get_data_parallel for coding, chunk 0
launching all workers
launching worker Process-1
launching worker Process-2
processing record PB.99.1|chr1:11796161-11810824(+)|i1a_c13849/f19p49/1138/RT|m.1, frame 0
launching worker Process-3
launching worker Process-4
Done with records
processing record PB.99.2|chr1:11796161-11810824(+)|i1a_c1909/f68p136/1135/RT|m.2, frame 0
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/SmartORF.py", line 35, in add_data_worker
processing record PB.99.4|chr1:11796161-11810824(+)|i1a_c49914/f6p67/1234/RT|m.4, frame 0
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/SmartORF.py", line 35, in add_data_worker
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/SmartORF.py", line 35, in add_data_worker
    stuff = ORFscores.make_data_smart(rec.seq, o_all, frame_shift=i)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/ORFscores.py", line 72, in make_data_smart
    stuff = ORFscores.make_data_smart(rec.seq, o_all, frame_shift=i)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/ORFscores.py", line 72, in make_data_smart
    arr = make_amino_scores(aa_freq)+make_diamino_scores(di_freq,o.diamino_range)+make_codon_scores(aa_freq,codon_freq)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/ORFscores.py", line 50, in make_codon_scores
    arr.append(aa_freq['*']*1./codon_freq[codon])
 arr = make_amino_scores(aa_freq)+make_diamino_scores(di_freq,o.diamino_range)+make_codon_scores(aa_freq,codon_freq)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/ORFscores.py", line 50, in make_codon_scores
    arr.append(aa_freq['*']*1./codon_freq[codon])
ZeroDivisionError: float division by zero
    stuff = ORFscores.make_data_smart(rec.seq, o_all, frame_shift=i)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/ORFscores.py", line 72, in make_data_smart
    arr = make_amino_scores(aa_freq)+make_diamino_scores(di_freq,o.diamino_range)+make_codon_scores(aa_freq,codon_freq)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/ORFscores.py", line 50, in make_codon_scores
    arr.append(aa_freq['*']*1./codon_freq[codon])
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/isg/shared/apps/angel/2.7/bin/angel_train.py", line 4, in <module>
    __import__('pkg_resources').run_script('Angel==2.7', 'angel_train.py')
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/EGG-INFO/scripts/angel_train.py", line 17, in <module>
    ANGEL_training(args.cds_filename, args.utr_filename, args.output_pickle, num_workers=args.cpus)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/SmartORF.py", line 100, in ANGEL_training
    data_pos = get_data_parallel(o_all, coding, [0], num_workers)
  File "/isg/shared/apps/angel/2.7/lib/python2.7/site-packages/Angel-2.7-py2.7-linux-x86_64.egg/Angel/SmartORF.py", line 65, in get_data_parallel
    obj = queue.get(timeout=60)
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 132, in get
    raise Empty

**Comment by Renxiaoliang** [comment]
Hi veravelasco, I have encountered the same problem with no ideas. Have you solved this?

**Comment by veravelasco** [comment]
Hi.  No, I was not able to solve it.  I just ended up using transedecoder.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
