### ISSUE TITLE
UnicodeDecodeError at angel_predict.py

### ISSUE THREAD

**Issue by yy-liang** [PacificBiosciences/ANGEL#36]
Hi @Magdoll,
I'm running the ANGEL v3.0 with the example data and I got the following error:

`$angel_predict.py test.fa MCF7_2015.dumb.final.training.pickle test_angel
Reading classifer pickle: MCF7_2015.dumb.final.training.pickle
/root/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.ensemble.weight_boosting module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)
/root/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.tree.tree module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.tree. Anything that cannot be imported from sklearn.tree is now part of the private API.
  warnings.warn(message, FutureWarning)
Traceback (most recent call last):
  File "/root/ANGEL/angel_predict.py", line 22, in <module>
    distribute_ANGEL_predict(args.fasta_filename, args.output_prefix, args.classifier_pickle, args.cpus, args.min_angel_aa_length, args.min_dumb_aa_length, args.use_rev_strand, args.output_mode, args.max_angel_secondORF_distance)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/Angel-3.0-py3.7-linux-x86_64.egg/Angel/SmartORF.py", line 254, in distribute_ANGEL_predict
    a = load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 1: ordinal not in range(128)`.

Any advice will be appreciated.

**Comment by Magdoll** [comment]
Hi @yy-liang ,
Oh my bad! The trained classifier pickles need to be updated for Python 3 version. Please don't use them for now. I am going to remove them from the GItHub in the meantime until a new one is up.
